package Oop.exceptionHandling;

public class Demo {
    public static void main(String[] args) {
        System.out.println(Main.divide(4,0));
        // the error msg displayed is based on what we gave Division by Adith
    }
}
